# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sleep_pb2 as sleep__pb2


class SleepTimeStub(object):
    """define service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sleep = channel.unary_unary(
                '/SleepTime/Sleep',
                request_serializer=sleep__pb2.Seconds.SerializeToString,
                response_deserializer=sleep__pb2.Seconds.FromString,
                )


class SleepTimeServicer(object):
    """define service
    """

    def Sleep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SleepTimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sleep': grpc.unary_unary_rpc_method_handler(
                    servicer.Sleep,
                    request_deserializer=sleep__pb2.Seconds.FromString,
                    response_serializer=sleep__pb2.Seconds.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SleepTime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SleepTime(object):
    """define service
    """

    @staticmethod
    def Sleep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SleepTime/Sleep',
            sleep__pb2.Seconds.SerializeToString,
            sleep__pb2.Seconds.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
